MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="===============3839859293789103635=="
From: support@glsvar.ru
To: sys@tehnosvar.ru
Subject: =?utf-8?b?0KHQldCg0JLQmNChINCe0KLQn9Cg0JDQktCa0Jgg0J/QmNCh0JXQnA==?=

--===============3839859293789103635==
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit

 Привет мир 

--===============3839859293789103635==
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

<html xmlns=3D"http://www.w3.org/1999/xhtml"><head>
      <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8=
">
      <meta name=3D"viewport" content=3D"width=3Ddevice-width, initial-scale=
=3D1.0">
      <title>=D0=A2=D0=B5=D1=85=D0=BD=D0=BE=D0=BB=D0=BE=D0=B3=D0=B8=D1=87=D0=
=B5=D1=81=D0=BA=D0=B8=D0=B9 =D1=86=D0=B5=D0=BD=D1=82=D1=80 =D0=A2=D0=B5=D1=85=
=D0=BD=D0=BE=D1=81=D0=B2=D0=B0=D1=80 =D0=9A=D0=A1</title>
      <style type=3D"text/css">
         /* Client-specific Styles */
         #outlook a {padding:0;} /* Force Outlook to provide a "view in brows=
er" menu link. */
         body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-=
size-adjust:100%; margin:0; padding:0;}
         /* Prevent Webkit and Windows Mobile platforms from changing default=
 font sizes, while not breaking desktop design. */
         .ExternalClass {width:100%;} /* Force Hotmail to display emails at f=
ull width */
         .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClas=
s font, .ExternalClass td, .ExternalClass div {line-height: 100%;} /* Force H=
otmail to display normal line spacing.  More on that: http://www.emailonacid.=
com/forum/viewthread/43/ */
         #backgroundTable {margin:0; padding:0; width:100% !important; line-h=
eight: 100% !important;}
         img {outline:none; text-decoration:none;border:none; -ms-interpolati=
on-mode: bicubic;}
         a img {border:none;}
         .image_fix {display:block;}
         p {margin: 0px 0px !important;}
        =20
         table td {border-collapse: collapse;}
         table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rs=
pace:0pt; }
         /*a {color: #e95353;text-decoration: none;text-decoration:none!impor=
tant;}*/
         /*STYLES*/
         table[class=3Dfull] { width: 100%; clear: both; }
        =20
         /*################################################*/
         /*IPAD STYLES*/
         /*################################################*/
         @media only screen and (max-width: 640px) {
         a[href^=3D"tel"], a[href^=3D"sms"] {
         text-decoration: none;
         color: #ffffff; /* or whatever your want */
         pointer-events: none;
         cursor: default;
         }
         .mobile_link a[href^=3D"tel"], .mobile_link a[href^=3D"sms"] {
         text-decoration: default;
         color: #ffffff !important;
         pointer-events: auto;
         cursor: default;
         }
         table[class=3Ddevicewidth] {width: 440px!important;text-align:center=
!important;}
         table[class=3Ddevicewidthinner] {width: 420px!important;text-align:c=
enter!important;}
         table[class=3D"sthide"]{display: none!important;}
         img[class=3D"bigimage"]{width: 420px!important;height:219px!importan=
t;}
         img[class=3D"col2img"]{width: 420px!important;height:258px!important=
;}
         img[class=3D"image-banner"]{width: 440px!important;height:106px!impo=
rtant;}
         td[class=3D"menu"]{text-align:center !important; padding: 0 0 10px 0=
 !important;}
         td[class=3D"logo"]{padding:10px 0 5px 0!important;margin: 0 auto !im=
portant;}
         img[class=3D"logo"]{padding:0!important;margin: 0 auto !important;}

         }
         /*##############################################*/
         /*IPHONE STYLES*/
         /*##############################################*/
         @media only screen and (max-width: 480px) {
         a[href^=3D"tel"], a[href^=3D"sms"] {
         text-decoration: none;
         color: #ffffff; /* or whatever your want */
         pointer-events: none;
         cursor: default;
         }
         .mobile_link a[href^=3D"tel"], .mobile_link a[href^=3D"sms"] {
         text-decoration: default;
         color: #ffffff !important;=20
         pointer-events: auto;
         cursor: default;
         }
         table[class=3Ddevicewidth] {width: 280px!important;text-align:center=
!important;}
         table[class=3Ddevicewidthinner] {width: 260px!important;text-align:c=
enter!important;}
         table[class=3D"sthide"]{display: none!important;}
         img[class=3D"bigimage"]{width: 260px!important;height:136px!importan=
t;}
         img[class=3D"col2img"]{width: 260px!important;height:160px!important=
;}
         img[class=3D"image-banner"]{width: 280px!important;height:68px!impor=
tant;}
        =20
         }
      </style>

     =20
   </head>
<body>

<div class=3D"block">
   <!-- image + text -->
   <table width=3D"100%" bgcolor=3D"#f6f4f5" cellpadding=3D"0" cellspacing=3D=
"0" border=3D"0" id=3D"backgroundTable" st-sortable=3D"bigimage">
      <tbody>
         <tr>
            <td>
               <table bgcolor=3D"#ffffff" width=3D"580" align=3D"center" cell=
spacing=3D"0" cellpadding=3D"0" border=3D"0" class=3D"devicewidth" modulebg=
=3D"edit">
                  <tbody>
                     <tr>
                        <td align=3D"center">
                           <a target=3D"_blank" href=3D"https://tehnosvar.ru"=
><img width=3D"100%" border=3D"0" height=3D"100%" alt=3D"" style=3D"display:b=
lock; border:none; outline:none; text-decoration:none;" src=3D"https://api.gl=
svar.ru/files/neuesJahr.jpg" class=3D"bigimage"></a>
                        </td>
                     </tr>
                  </tbody>
               </table>
            </td>
         </tr>
      </tbody>
   </table>
</div>

<div class=3D"block">
   <!-- start of header -->
   <table width=3D"100%" bgcolor=3D"#f6f4f5" cellpadding=3D"0" cellspacing=3D=
"0" border=3D"0" id=3D"backgroundTable" st-sortable=3D"header">
      <tbody>
         <tr>
            <td>
               <table width=3D"580" bgcolor=3D"#1b395c" cellpadding=3D"0" cel=
lspacing=3D"0" border=3D"0" align=3D"center" class=3D"devicewidth" hlitebg=3D=
"edit" shadow=3D"edit">
                  <tbody>
                     <tr>
                        <td>
                           <!-- logo -->
                           <table width=3D"280" cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" align=3D"center" class=3D"devicewidth">
                              <tbody>
                                 <tr>
                                    <td valign=3D"middle" width=3D"270" style=
=3D"padding: 10px 0 10px 20px;" class=3D"logo">
                                       <div class=3D"imgpop" align=3D"center">
                                          <a href=3D"https://tehnosvar.ru" ta=
rget=3D"blank"><img src=3D"https://api.glsvar.ru/files/mail/logo.jpeg" alt=3D=
"logo" width=3D"150" border=3D"0" style=3D"display:block; border:none; outlin=
e:none; text-decoration:none;" st-image=3D"edit" class=3D"logo"></a>
                                       </div>
                                    </td>
                                 </tr>
                              </tbody>
                           </table>
                        </td>
                     </tr>
                  </tbody>
               </table>
            </td>
         </tr>
      </tbody>
   </table>
   <!-- end of header -->
</div>

</body></html>

--===============3839859293789103635==--
